export const namesOne = {
    0: "Tiger",
    1: "Wolf",
    2: "Bear", 
    3: "Shark", 
    4: "Cat",
    5: "Dog", 
    6: "Silver", 
    7: "Gold", 
    8: "Copper", 
    9: "Brass",
    10: "Xeon",
    11: "Space",
    12: "Rocket",
    13: "Star",
    14: "Volts",
    15: "Computer",
    16: "Forest",
    17: "River",
    18: "Tree",
    19: "[YOUR NAME] "
}

export const namesTwo = {
    0: "Life", 
    1: "Records", 
    2: "Programmers", 
    3: "Limited", 
    4: "Development", 
    5: "World",
    6: "Media", 
    7: "Developer", 
    8: "Creators", 
    9: "WebDev",
    10: "Ocean",
    11: "Beach",
    12: "Launch",
    13: "Holder",
    14: "Corp",
    15: "Cyber",
    16: "Graphics",
    17: "Shop",
    18: "Jet",
    19: "Whiskers"
}